### ISSUE TITLE
Incompatible with EdgeHTML 16

### ISSUE THREAD

**Issue by bodograumann** [sindresorhus/p-event#25]
I get an error when trying to use `p-event` with EdgeHTML 16. Looking at the code, I think it is the use of the `...args` / rest syntax.

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

If you use Create React App, upgrade to [Create React App v2](https://reactjs.org/blog/2018/10/01/create-react-app-v2.html). It supports automatic transpilation of dependencies, which will make this package *just work*.

**Comment by bodograumann** [comment]
I am using vue-cli and it also allows for transpilation of dependencies, but is only intended for ES modules. So I worked around that by transforming `p-event` into an ES module with `patch-package` and then transpiling. Really not an ideal solution. Maybe I’ll look for a replacement lib which is targeting the browser.
