### ISSUE TITLE
Can't build with this as a dependency

### ISSUE THREAD

**Issue by jdoklovic** [sindresorhus/p-event#26]
`./node_modules/p-event/index.js
Module parse failed: Unexpected token (29:3)
You may need an appropriate loader to handle this file type.
|                       multiArgs: false,
|                       resolveImmediately: false,
|                       ...options
|               };
|`

**Comment by sindresorhus** [comment]
That's a problem with your bundler, not this code. The module runs fine on Node.js.

**Comment by jdoklovic** [comment]
It would be nice if es modules were provided as well. Otherwise I have to transpile this from the node_modules directory which isn't great
