### ISSUE TITLE
Emitter "succeeding" but returning undefined

### ISSUE THREAD

**Issue by robross0606** [sindresorhus/p-event#29]
I'm using p-Event like this:
```js
const httpServer = await pEvent(server.koaApp.listen(config.server.port), 'listening')
```
The `'listening'` event is triggering but the result in `httpServer` is `undefined`.  What am I doing wrong?

**Comment by sindresorhus** [comment]
You might need to bind the `.listen` method to the `koaApp` instance:

```js
const httpServer = await pEvent(server.koaApp.listen.bind(server.koaApp, config.server.port), 'listening')
```

**Comment by sindresorhus** [comment]
> Also, does p-event have a way to handle situations where the emitter function also returns a value?

No, I have never seen an API like that, so I don't think it's common enough to support such a thing.
