### ISSUE TITLE
Ability to identify a timeout error

### ISSUE THREAD

**Issue by mjlescano** [sindresorhus/p-event#31]
Right now, the only way to identify the error (that I can think of) as a timeout error instead of an error thrown by my emitter or the filter is by checking the `err.message` and I'm not totally comfortable using the message:

```javascript
try {
  const result = await pEvent(emitter, 'finish');
  console.log(result);
} catch (err) {
  if (err.message.startsWith('Promise timed out after')) {
    // Do something specific for timeout errors
  }
}
```

For a clearer and safer way to doing this check, I could send PRs with one or both of these solutions:
1. Expose `module.exports.TimeoutError = pTimeout.TimeoutError` to be able to do `err instanceof TimeoutError` without having to add the `p-timeout` dependency.
2. Add on the module `p-timeout` a `err.code = 'TIMEOUT_ERROR'` to be able to check it by the `code`

**Comment by sindresorhus** [comment]
You can already check `error.name === 'TimeoutError`, but I agree it would be nice to do `1`.

**Comment by mjlescano** [comment]
Oh nice, didn't realize I could use the `name` :) I will be sending a PR for `1` also. Thanks!
