### ISSUE TITLE
Undefined rejection

### ISSUE THREAD

**Issue by tjr5269** [sindresorhus/p-event#33]
I'm trying to handle custom rejection events. When either of the events in rejection events fires, the error is undefined. The timeout failure does work properly.

```javascript
try {
    await pEvent(this, 'submit-success', {
         rejectionEvents: ['submit-failure', 'submit-cooldown'],
         timeout: 30000
    });
    console.log('Submit success');
} catch (error) {
    console.log(error);
    if (error instanceOf pEvent.TimeoutError) {
        console.log('this was a timeout')
    }
    if (error === 'submit-cooldown') {
        //How do I get to here?
    }
}
```

**Comment by papb** [comment]
Are you sure your emitter is emitting these failure events? If yes, what is logged in the `console.log(error)`? Please provide a minimal complete example, thanks!
