### ISSUE TITLE
Thoughts on pattern matching

### ISSUE THREAD

**Issue by kmalakoff** [sindresorhus/p-event#5]
I have a case where I'm listening to an event emitter, but waiting for a specific pattern in the emitted data. Is this a case that you would be interested in supporting with this module?

```
pEvent(emitter, 'eventname', (data) => data.id === 5).then(() => {});
```

**Comment by sindresorhus** [comment]
Yes, definitely. PR welcome. It was discussed in https://github.com/sindresorhus/p-event/issues/3#issuecomment-301552263.

**Comment by kmalakoff** [comment]
Cool. I'll submit a PR today with some tests.
